name: GH Project cleanup action
description: Archive old cards from Github projects
inputs:
  config:
    description: YAML-formatted config for gh-project-cleanup
    required: true

runs:
  using: "composite"
  steps:
    - name: Write config from inputs
      shell: bash
      run: |
        echo $INPUT_CONFIG | tee projects.yml
    - name: Install dependencies
      run: |
        apt install python3-setuptools
        pip3 install -r requirements.txt
      shell: bash
    - run: ./ghp-cleanup.py projects.yml
      shell: bash
