name: GH Project cleanup action
description: Archive old cards from Github projects
inputs:
  config:
    description: YAML-formatted config for gh-project-cleanup
    required: true
  github_token:
    description: Github token with enough permissions to work on the dashboard
    required: true

runs:
  using: docker
  image: roobre/gh-project-cleanup
  env:
    CONFIG: ${{ inputs.config }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
