on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    name: Build and push dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build . -t roobre/gh-project-cleanup
      - uses: docker/login-action@v1
        with:
          username: roobre
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker push roobre/gh-project-cleanup

  self-test:
    needs: [ release ]
    name: Example and self-test job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config: |
            # Project path
            roobre/1:
              Done: # Column matches partially
                older_than: 2 months # Format must be understandable by https://pypi.org/project/durations-nlp/
